server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: forzatune-pro-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/forzatune_pro?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  security:
    user:
      name: admin
      password: admin

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.forzatune.backend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
jwt:
  secret: forzatune-pro-secret-key-2024-very-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

# Auth Configuration
auth:
  dev-mode: false # 开发模式：true=跳过认证，false=正常认证

# Logging Configuration
logging:
  level:
    root: INFO
    com.forzatune.backend: DEBUG
    com.forzatune.backend.controller: INFO
    com.forzatune.backend.service: DEBUG
    com.forzatune.backend.mapper: DEBUG
    com.forzatune.backend.exception: ERROR
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.apache.ibatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true 